In [1]:
import torch
import torch.nn.functional as F

In [20]:
torch.manual_seed(1)

## Calculate softmax function (Low lvl)

In [21]:
z = torch.FloatTensor([1, 2, 3])

In [22]:
hypothesis = F.softmax(z, dim=0)
print(hypothesis)

tensor([0.0900, 0.2447, 0.6652])


In [23]:
hypothesis.sum()

tensor(1.)

In [24]:
# create 3x5 tensor
z = torch.rand(3,5,requires_grad=True)

In [25]:
hypothesis = F.softmax(z, dim=1)
print(hypothesis) # The sum will be 1

tensor([[0.2645, 0.1639, 0.1855, 0.2585, 0.1277],
        [0.2430, 0.1624, 0.2322, 0.1930, 0.1694],
        [0.2226, 0.1986, 0.2326, 0.1594, 0.1868]], grad_fn=<SoftmaxBackward>)


In [26]:
y = torch.randint(5, (3,)).long()
print(y)

tensor([0, 2, 1])


In [27]:
# one-hot encoding for each label
y_one_hot = torch.zeros_like(hypothesis) 
y_one_hot.scatter_(1, y.unsqueeze(1), 1)

tensor([[1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 1., 0., 0., 0.]])

In [30]:
print(y.unsqueeze(1))

tensor([[0],
        [2],
        [1]])


In [31]:
print(y_one_hot)

tensor([[1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 1., 0., 0., 0.]])


In [32]:
cost = (y_one_hot * -torch.log(hypothesis)).sum(dim=1).mean()
print(cost)

tensor(1.4689, grad_fn=<MeanBackward0>)


## Calculate softmax function (High lvl)

#### 1. F.softmax() + torch.log() = F.log_softmax()

In [34]:
# low level
torch.log(F.softmax(z, dim=1))

tensor([[-1.3301, -1.8084, -1.6846, -1.3530, -2.0584],
        [-1.4147, -1.8174, -1.4602, -1.6450, -1.7758],
        [-1.5025, -1.6165, -1.4586, -1.8360, -1.6776]], grad_fn=<LogBackward>)

In [35]:
# high level
F.log_softmax(z, dim=1)

tensor([[-1.3301, -1.8084, -1.6846, -1.3530, -2.0584],
        [-1.4147, -1.8174, -1.4602, -1.6450, -1.7758],
        [-1.5025, -1.6165, -1.4586, -1.8360, -1.6776]],
       grad_fn=<LogSoftmaxBackward>)

#### 2. F.log_softmax() + F.nll_loss() = F.cross_entropy()

In [36]:
# low level
(y_one_hot * -torch.log(F.softmax(z, dim=1))).sum(dim=1).mean()

tensor(1.4689, grad_fn=<MeanBackward0>)

In [37]:
# low level with F.log_softmax()
(y_one_hot * - F.log_softmax(z, dim=1)).sum(dim=1).mean()

tensor(1.4689, grad_fn=<MeanBackward0>)

In [38]:
# high level with F.nll_loss()
F.nll_loss(F.log_softmax(z, dim=1), y)

tensor(1.4689, grad_fn=<NllLossBackward>)

In [39]:
# F.cross_entropy()
F.cross_entropy(z, y)

tensor(1.4689, grad_fn=<NllLossBackward>)